[package]
name = "free-whisper-audio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cpal.workspace = true
free-whisper-domain = { path = "../domain" }
rubato.workspace = true
serde.workspace = true
thiserror.workspace = true
wavekat-vad.workspace = true
